version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: drawapp-postgres
    environment:
      POSTGRES_DB: drawapp
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pratham
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  
volumes:
  pgdata:
